biochezvous/accueil/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('accueil', views.accueil, name='accueil'),
    path('', views.accueil, name='accueil2'),

    path('propos', views.propos, name='propos'),

]

biochezvous/biochezvous/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('espace_perso.urls')),
    path('', include('produit.urls')   ),
    path('', include('accueil.urls')   ),
    path('', include('espace_admin.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biochezvous/espace_perso/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from . import views
from . import utils

urlpatterns = [
    #Connexions/Inscriptions
    path('inscription',                     views.inscription_user,     name='inscription_user'),
    path('inscription/producteur',          views.inscription_prod,     name='inscription_prod'),
    path('connexion',                       views.connexion,            name='connexion'),
    path('connexion',                       auth_views.LoginView.as_view()),
    path('deconnexion',                     views.deconnexion,          name='deconnexion'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('confirmation',                   views.confirmation,          name='confirmation'),
    #Utilisateur        
    path('profil',                          views.espacePerso,          name='espacePerso'),
    path('profil/edit',                     views.informationPerso,     name='informationPerso'),
    path('profil/adresse/edit',             views.ajout_prod_adresse,   name='ajout_prod_adresse'),
    path('profil/mesPreferences',             views.preferences,   name='mesPreferences'),
    #Producteur
    path('profil/producteur/commandes',     views.commandeProducteur,   name='commandeProducteur'),
    path('producteur/terminerCommander/<int:commande_id>',views.terminerCommande,name='terminerCommande'),
    #Panier/Commande
    path('profil/panier',                   views.panier,               name='panier'),
    path('profil/panier/<int:id>/suppression',views.suppressionPanier,  name='suppressionPanier'),
    path('profil/panier/commander',         views.commander,            name='commander'),
    path('profil/panier/paiement',          views.paiement,             name='paiement'),
    path('profil/commandes',                views.listeCommande,        name='listecommande'),
    path('profil/commande/<int:id>',        views.commande,             name='commande'),
    path('profil/panier/varier',            views.varierArticlePanier,  name='varierArticlePanier'),
    path('send_mail_commande/<int:commande_id>',views.send_mail_commande,name='send_mail_commande'),
    path('profil/commanderEncore/<int:id>',        views.commanderEncore,             name='commanderEncore'),
    #Catalogue
    path('producteur/<int:idProducteur>',   views.producteur,           name='producteur'),
    #Administration
    path('personne/<int:id>/supprimer',     views.deleteOneUser,     name='deleteOneUser'),
    path('aide',                    views.aide,                 name='aide'),
    #Factures
    path('pdf_view/<int:id>',       views.PDF,                  name="pdf_view"),
    
]

biochezvous/espace_perso/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import Group, Permission, PermissionsMixin, UserManager


class Personne(AbstractBaseUser, PermissionsMixin):
    personne_id = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    mail = models.EmailField(max_length=100, unique=True)
    num_tel = models.CharField(max_length=100)
    newsletter = models.BooleanField()
    confirmation = models.BooleanField()
    panier = models.ManyToManyField('produit.Produit', through='produit.Panier')

    USERNAME_FIELD = 'mail'
    objects = UserManager()

    
    class Meta:
        db_table = 'personne'
        default_permissions = ()

class Administrateur(Personne):

    class Meta:
        db_table = 'administrateur'
        default_permissions = ()
        permissions = [
            ('can_view_espace_admin', 'Peux acceder a la page espace admin'),
        ]

class Utilisateur(Personne):

    class Meta:
        db_table = 'utilisateur'
        default_permissions = ()
        permissions = [
            ('can_view_espace_perso', 'Peux acceder a la page espace perso'),
        ]

class Producteur(Personne):
    description = models.TextField()
    image   = models.ImageField(upload_to='images/')
    iban = models.CharField(max_length=100)
    class Meta:
        db_table = 'producteur'
        default_permissions = ()
        permissions = [
            ('can_view_espace_perso', 'Peux acceder a la page espace perso'),
            ('can_view_espace_producteur', 'Peux acceder a la page espace producteur'),
        ]


class Adresse(models.Model):
    personne = models.OneToOneField('Personne', on_delete=models.CASCADE, related_name='adresse')
    code_postal = models.CharField(max_length=10, blank=True)
    ville  = models.CharField(max_length=60, blank=True)
    adresse = models.CharField(max_length = 100,  blank=True)
    lat = models.FloatField(blank=True, null=True)
    lon = models.FloatField(blank=True, null=True)
    class Meta:
        db_table = 'adresse'
        default_permissions = ()

class Preference(models.Model):
    produit  = models.ForeignKey('produit.Produit', on_delete=models.CASCADE)
    personne = models.ForeignKey('Personne', on_delete=models.CASCADE)

    class Meta:
        db_table = 'preference'
        default_permissions = ()

biochezvous/espace_perso/forms.py
from django import forms
from django.forms import ModelForm
from .models import Utilisateur, Personne, Producteur
from espace_admin.models import Demandes
from produit.models import Image
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from .utils import getCoords
from .models import Adresse
from produit.models import Produit
from PIL import Image as PILImage



class FormInscription(UserCreationForm):
    
    class Meta:
        model = Personne
        fields = ['nom','prenom','mail','num_tel']

class FormConnexion(AuthenticationForm):
    username=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 container-fluid'}))
    password=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 container-fluid','type':'password'}))
    class Meta:
        model = Personne
        fields = ['username', 'password']

class FormInscriptionProd(UserCreationForm):
    nom=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))
    prenom=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))
    mail=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))
    num_tel=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control col-md-12 '}))
    iban = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))
    image=forms.ImageField(max_length=None,allow_empty_file=".jpg, .jpeg, .png", required=False)

    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)
    def save(self):
        user = super(FormInscriptionProd, self).save(commit=False)
        prod_group, created = Group.objects.get_or_create(name='producteur')
        #TODO : mettre confirmation a False
        user.confirmation = True
        user.newsletter = True
        user.save()
        user.groups.add(prod_group)
        if created:
            permissions_producteur = Permission.objects.filter(content_type=ContentType.objects.get(app_label='espace_perso', model='producteur').id)
            prod_group.permissions.set(permissions_producteur)
        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        if x==None or y==None or w==None or h==None :
            x, y, w, h = 0, 0, 100, 100
        image = PILImage.open(user.image)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), PILImage.ANTIALIAS)
        user.save()
        resized_image.save(user.image.path)
        return user
    class Meta:
        model = Producteur
        fields = ['nom', 'prenom', 'mail', 'num_tel','description','image','iban', 'x', 'y', 'width', 'height']

class FormInscriptionUser(UserCreationForm):
    
    nom=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))
    prenom=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))
    mail=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))
    num_tel=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))
    def save(self):
        user = super().save(commit=False)
        user_group, created = Group.objects.get_or_create(name='utilisateur')
        #TODO : mettre confirmation a False
        user.confirmation = True
        user.newsletter = True
        user.save()
        user.groups.add(user_group)
        user.save()
        if created:
            permissions_utilisateur = Permission.objects.filter(content_type=ContentType.objects.get(app_label='espace_perso', model='utilisateur').id)
            user_group.permissions.set(permissions_utilisateur)
        return user
    def __init__(self, *args, **kwargs):
        super(FormInscriptionUser, self).__init__(*args, **kwargs)
        self.initial['confirmation'] = 1

    class Meta:
        model = Personne
        fields = ['nom','prenom','mail','num_tel']


class FormDataModification(ModelForm):
    
    nom = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))
    prenom = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12'}))
    num_tel = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12'}))
    
    class Meta:
        model = Personne
        fields = ['nom','prenom','num_tel',]


class FormSelectionQuantite(ModelForm):
    quantite = forms.CharField(initial='1')
    class Meta:
        model = Produit 
        fields = ['quantite']


class FormDataModifProd(ModelForm):
    
    nom=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))
    prenom=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))

    num_tel=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control col-md-12 '}))
    image=forms.ImageField(max_length=None,allow_empty_file=".jpg, .jpeg, .png", required=False)
    iban = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))

    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    def save(self):

        instance = super(FormDataModifProd, self).save(commit=False)
        
        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        if x==None or y==None or w==None or h==None :
            x, y, w, h = 0, 0, 100, 100


        image = PILImage.open(instance.image)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), PILImage.ANTIALIAS)
        instance.save()
        resized_image.save(instance.image.path)
        return instance

    class Meta:
        model = Producteur
        fields = ['nom', 'prenom','num_tel','description','image','iban', 'x', 'y', 'width', 'height']
    
class FormAide(forms.ModelForm):
    nom = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-6 container-fluid'}))
    prenom = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-6 container-fluid'}))
    mail = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-6 container-fluid'}))
    objet = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-6 container-fluid'}))
    message = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-6 container-fluid'}))

    class Meta:
        model = Demandes
        fields = ['nom', 'prenom', 'mail', 'objet','message']
    


class AdresseModifForm(ModelForm):
    adresse = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))
    ville = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))
    code_postal = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control col-md-12 '}))

    def save(self, commit=True):
        instance = super().save(commit)
        instance.lat, instance.lon = getCoords(instance.adresse, instance.ville, instance.code_postal)
        return instance

    class Meta:
        model = Adresse
        fields = ['code_postal','ville','adresse',]

biochezvous/espace_perso/templates/espace_perso/ajout_adresse.html
{% extends "produit/base.html" %}

{% block title %}Données personnelles{% endblock %}

{% block content %}
<div class="container-fluid">

    <div id="espacePersoTitle" class="section-title" data-aos="fade-in" data-aos-delay="100">
        <h2>Ajout d'une adresse</h2>
    </div>

    {% include 'espace_perso/messages.html' %}

    
    <div class="row">
        <div class="col formulaire">
            <div class="form-group"> 
                <form  method="post" >
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br>
                    <button class="btn-formulaire" type="submit">Enregistrer les modifications</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

biochezvous/espace_perso/templates/espace_perso/commande.html
{% extends "produit/base.html"%}
{% load static %}
{% load math_filters %}

{% block title %}Détails commande{% endblock %}

{% block content %}



<div class="container">

  <div class="row">
    <div class="col">
      <div id="espacePersoTitle" class="section-title" data-aos="fade-in" data-aos-delay="100">
        <h2> Commande  n° {{ Commande.commande_id }} </h2>
      </div>
    </div>
  </div>
  
  {% include 'espace_perso/messages.html' %}

<div class="row">
  <div class="col">
    <table class="table cmd">
      <thead>
        <tr>
          <th scope="col">Produit</th>
          <th scope="col">Prix unitaire</th>
          <th scope="col">Quantite</th>
          <th scope="col">Sous-Total</th>
        </tr>
      </thead>
      <tbody>
  
        {% for ctn in contenuCommande %}
  
        <tr>
  
          <td>
            <p> {{ ctn.produit.nom }}</p>
            <p> {{ ctn.produit.description }}</p>
          </td>
          <td>{{ ctn.produit.prix }}</td>
          <td>{{ ctn.quantite }}</td>
          <td>{{ ctn.produit.prix|mul:ctn.quantite }}</td>
  
        </tr>
        {% endfor %}
        <tr>
          <td></td>
          <td></td>
          <td> Total commande </td>
          <td> {{ Commande.montant }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
  

  {% endblock %}

biochezvous/espace_perso/templates/espace_perso/commandeProd.html
{% extends "produit/base.html"%}
{% load static %}

{% block title %}Liste des commandes {% endblock %}

{% block content %}

{% if listecommandes %}

<div class="container-fluid mt-5" id="commandeProd">

    <div id="espacePersoTitle" class="section-title" data-aos="fade-in" data-aos-delay="100">
        <h2> MES COMMANDES </h2>
      </div>
<table id="table" class="table table-hover table-mc-light-blue">
    <thead>
        <tr>
            <th> Id commande </th>
            <th> Date </th>
            <th> Montant </th>
            <th>Id acheteur</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for commande in listecommandes %}
        <tr>

            <th>{{commande.commande_id }}</th>
            <th>{{commande.date }}</th>
            <th>{{commande.montant}}</th>
            <th>{{commande.personne.nom}}</th>
            {% if commande.statut is 1 %}
            <td>
                <button type="button" class="btn-formulaire"><a href="{% url 'terminerCommande' commande.commande_id %}"> Commande
                        retirée </a></button>
            </td>
            {% else %}
            <td>
                <button type="button" class="btn-formulaire"><a href="{% url 'send_mail_commande' commande.commande_id %}"> Commande
                        prête </a></button>
            </td>
            {% endif %}

            
        </tr>
        {% for com in listeproduits %}
        <tr>
            <td>{{com.commande_id }}</td>
            <td>{{com.quantite }}</td>
            <td>{{com.produit.nom}}</td>
            <td>{{com.produit.stock}}</td>
            <td></td>
            <td></td>               
        </tr>
        {% endfor %}
{% endfor %}
</tbody>
</table>
{% else %}
<div class="row justify-content-center text-center">
    <div class="col-md-6">
      <p> Vous n'avez pas pas de commandes à préparer.</p>
    </div>
  </div>
  {% endif %}


{% endblock %}

biochezvous/espace_perso/templates/espace_perso/confirmation.html
{% extends "produit/base.html"%}
{% load static %}

{% block title %}Bienvenue{% endblock %}

{% block content %}

<div class="section-title" data-aos="fade-in" data-aos-delay="100">
    <h2>Bienvenue !</h2>
    <p>Veuillez confirmer votre adresse mail pour finaliser votre inscription</p>
</div>

{% endblock %}

biochezvous/espace_perso/templates/espace_perso/demande_aide.html
{% extends "produit/base.html" %}
{% load static %}

{% block title %}Demande d'aide{% endblock %}


{% block content %}
<br>
<div class="container-fluid">

    <div id="espacePersoTitle" class="section-title" data-aos="fade-in" data-aos-delay="100">
        <h2> Espace personnel - Contacter le SAV</h2>
    </div>

    <div class="text-center">
        <h5>Vous rencontrez un problème sur BioChezVous ? Parlez-en via ce formulaire de contact ! Nous serons ravis de vous aider.</h5>
        <p>Nous voulons épauler au mieux nos producteurs et leurs clients.</p>
    </div>
    <br>
    <form method="POST" class="text-center post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary " type="submit">Envoyer ma demande</button>
    </form>

    <br>
</div>
{% endblock %}

biochezvous/espace_perso/templates/espace_perso/espacePerso.html
{% extends "produit/base.html"%}
{% load static %}

{% block title %}Mon espace{% endblock %}

{% block content %}



<div class="container-fluid">

    <div id="espacePersoTitle" class="section-title" data-aos="fade-in" data-aos-delay="100">
        <h2> Espace personnel </h2>
    </div>


    <div class="row justify-content-around text-center">
        
        <a href="{% url 'listecommande' %}" class="col-md-3 boxEspacePerso">                
            <div>
                <i class="icofont-bar-code"></i>
                <p> Historique des commandes </p>                
            </div>                
        </a>
        
        <a href="{% url 'informationPerso' %}" class="col-md-3 boxEspacePerso">
            <div>
                <i class="icofont-address-book"></i>                
                <p> Mes informations </p>
            </div>           
        </a>

        <a href="{% url 'ajout_prod_adresse' %}" class="col-md-3 boxEspacePerso">
            <div>
                <i class="icofont-pencil"></i>
                <p> Modifier mon adresse </p>
            </div>
        </a>
    </div>

    <div class="row justify-content-around text-center">
        <a href="{% url 'mesPreferences' %}" class="col-md-3 boxEspacePerso">
            <div>
                <i class="icofont-heart"></i>
                <p> Mes produits favoris </p>                
            </div>            
        </a>

        <a href="#" class="col-md-3 boxEspacePerso">
            <div>
                <i class="icofont-finger-print"></i>
                <p> RGPD </p>
            </div>
        </a>
        
        <a href="#" class="col-md-3 boxEspacePerso">
            <div>
                <i class="icofont-alarm"></i>
                <p> Mes alertes </p>                
            </div>            
        </a>

    </div>





</div>
{% endblock %}

biochezvous/espace_perso/templates/espace_perso/espaceProd.html
{% extends "produit/base.html" %}
{% load static %}
{% block title %}Espace Producteur{% endblock %}
{% block content %}
<div class="container admin">
    <div class="row">
        <div class="col">
            <div class="section-title" data-aos="fade-in" data-aos-delay="100">
                <h2>Espace producteur</h2>
            </div>
        </div>
    </div>
    
    <div class="row justify-content-around text-center">
        
        <a href="{% url 'ajout_categorie' %}" class="col-md-3 boxEspacePerso">                
            <div class=" ">
                <i class="icofont-bar-code"></i>
                <p> Ajouter une catégorie </p>                
            </div>                
        </a>
        
        <a href="{% url 'informationPerso' %}" class="col-md-3 boxEspacePerso">
            <div>
                <i class="icofont-address-book"></i>                
                <p> Mes informations </p>
            </div>           
        </a>

        <a href="{% url 'ajout_prod_adresse' %}" class="col-md-3 boxEspacePerso">
            <div>
                <i class="icofont-edit"></i>
                <p> Modifier mon adresse </p>
            </div>
        </a>
    </div>

    <div class="row justify-content-around text-center">
        <a href="{% url 'ajout_prod' %}" class="col-md-3 boxEspacePerso">
            <div>
                <i class="icofont-ui-add"></i>
                <p> Ajouter un produit </p>
            </div>
        </a>
        <a href="{% url 'aff_prod' %}" class="col-md-3 boxEspacePerso">
            <div>
                <i class="icofont-listine-dots"></i>
                <p> Liste de mes produits </p>                
            </div>            
        </a>
        <a href="{% url 'commandeProducteur' %}" class="col-md-3 boxEspacePerso">
            <div>
                <i class="icofont-list"></i>
                <p> Voir les commandes </p>                
            </div>            
        </a>

    </div>
    
</div>
{% endblock %}

biochezvous/espace_perso/templates/espace_perso/informationProd.html
{% extends "produit/base.html"%}
{% load static %}

{% block title %}Mon espace{% endblock %}

{% block content %}


<div class="container-fluid">

    <div id="espacePersoTitle" class="section-title" data-aos="fade-in" data-aos-delay="100">
        <h2> Espace personnel du producteur</h2>
    </div>
<div class="row">
    <div class="col formulaire">
        <div class="form-group">
            <form  method="post" enctype="multipart/form-data" id="formUpload">
                {% csrf_token %}
                {{ form.as_p }}
                <br>
                <button class="btn-formulaire" type="submit">Enregistrer mes infos</button>
            </form>
        </div>
    </div>
</div>
</div>

<div class="modal fade" id="modalCrop">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Redimensionner l'image</h4>
                </div>
                <div class="modal-body">
                    <img src="" id="image" style="max-width: 100%;">
                </div>
                <div class="modal-footer">
                    <div class="btn-group pull-left" role="group">
                    <button type="button" class="btn btn-default js-zoom-in">
                        <span class="glyphicon glyphicon-zoom-in"></span>
                    </button>
                    <button type="button" class="btn btn-default js-zoom-out">
                        <span class="glyphicon glyphicon-zoom-out"></span>
                    </button>
                    </div>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Abandonner</button>
                    <button type="button" class="btn btn-primary js-crop-and-upload">Redimensionner et mettre en ligne</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block morescripts %}
<script>
$(function () {

    /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
    $("#id_image").change(function () {
    if (this.files && this.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
        }
        reader.readAsDataURL(this.files[0]);
    }
    });
    $("#id_image").click(function () {
    if (this.files && this.files[0]) {
        $("#id_image").val(null);
    }
    });

    /* SCRIPTS TO HANDLE THE CROPPER BOX */
    var $image = $("#image");
    var cropBoxData;
    var canvasData;
    $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
        viewMode: 1,
        aspectRatio: 1/1,
        minCropBoxWidth: 200,
        minCropBoxHeight: 200,
        ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
        }
        });
    }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
    });

    $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
    });

    $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
    });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
    $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#modalCrop").modal("hide");
    });

    });
</script>
{% endblock morescripts %}

biochezvous/espace_perso/templates/espace_perso/statut.html
{% block content %}
        {% if cmd.statut is 0 %}
        <span class="badge badge-info">Validée</span>
        {% endif %}
        {% if cmd.statut is 1 %}
        <span class="badge badge-success">Prête</span>
        {% endif %}
        {% if cmd.statut is 2 %}
        <span class="badge badge-success">Retirée</span>
        {% endif %}
{% endblock %}

biochezvous/espace_perso/templates/espace_perso/test.html
<!DOCTYPE html>
<html>
<head>
	<title>HTML Tp PDF</title>
	<!-- Latest compiled and minified bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<style>
		body{
			background-color: #764ba2;
		}

		.card{
			background-color: #fff;
			padding: 50px 50px 50px 50px;
			margin:50px;
		}
	</style>
</head>

<body  >
	<div class="container">
		<div class="row">
			<div class="col-md"></div>

			<div class="col-md">
				<div class="card card-body">
					 <div class="text-center"> 
					<h3>View Invoices or download directly to PDF</h3>
					<p>Turn HTML templates into PDF's with Django + XHTML 2 PDF. This example gives you the option of  <br> view a template as a PDF or Downloading directly.</p>
					<a class="btn btn-info" href="{% url 'pdf_view' %}" target="_blank">View Invoice</a>
					<a class="btn btn-info"  href="{% url 'pdf_download' %}">Download Invoice</a>
					</div>
				</div>
			</div>

			<div class="col-md"></div>
		</div>
	</div>


</body>
</html>